# docker-compose.yml
version: '3.8'

services:

  mysql-users:
    image: mysql:8
    container_name: mysql-users
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: usuario
    ports:
      - "3307:3306"
    volumes:
      - usersdb_data:/var/lib/mysql
    
    networks:
      - hotel-net

  # Microservicio de Habitaciones
  habitacion-service:
    build:
      context: ./habitacion-service
      dockerfile: Dockerfile
    container_name: habitacion-service
    restart: on-failure
    env_file:
      - ./habitacion-service/.env
    ports:
      - '4000:4000'
    networks:
      - hotel-net
  #hola mundo
  # usuarios
  usuarios-service:
    build:
      context: ./usuarios-service
      dockerfile: Dockerfile
    container_name: usuarios-service
    restart: on-failure
    env_file:
      - ./usuarios-service/.env
    depends_on:
      - mysql-users
    ports:
      - '8000:8000'
    networks:
      - hotel-net

  # Microservicio de Hoteles
  hotel-service:
    build:
      context: ./hotel-service
      dockerfile: Dockerfile
    container_name: hotel-service
    restart: on-failure
    env_file:
      - ./hotel-service/.env
    ports:
      - '5000:5000'
    networks:
      - hotel-net

  # Frontend React+Vite
  frontend:
    build:
      context: ./IngenieriadeSoftware
      dockerfile: Dockerfile
    container_name: hotel-frontend
    restart: unless-stopped
    env_file:
      - ./IngenieriadeSoftware/.env
    ports:
      - '3000:80'
    networks:
      - hotel-net

volumes:
  usersdb_data:

networks:
  hotel-net:
    driver: bridge
